# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6452437d0b72bb8e7ab0f2681b605d1480a2af0bb1030a1dc4f95ee6c2cd52b0b1132c304895d410d31d40deacf4a32ba51666045421a93a8b9f2e9d922ec3c

test:
  secret_key_base: 75de86b2a0efab8074f9c43363e163b3537c78e95c7348a7c72ddc3891628f5f1d6f179239211f99464bac65f1fa7d6ce489b1b42101dc97aa059b4fa94569de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
